### ISSUE TITLE
returning `Result<impl Trait>` from a `#[autometrics]`'d function results in compile error

### ISSUE THREAD

**Issue by mellowagain** [autometrics-dev/autometrics-rs#121]
if one has a function that looks like this:

```rust
#[autometrics]
async fn hello() -> Result<impl ToString, std::io::Error> {
    // ...
}
```

the compiler will fail to compile it with:

```
error[E0562]: `impl Trait` only allowed in function and inherent method return types, not in variable bindings
  --> src/main.rs:11:28
   |
11 | async fn hello() -> Result<impl ToString, std::io::Error> {
   |                            ^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0562`.
error: could not compile `playground` (bin "playground") due to previous error
```

removing the `#[autometrics]` macro ends up making the program compile successfully.

playgrounds:
- smallest example: https://www.rustexplorer.com/b/52t7cy
- with `actix-web`: https://www.rustexplorer.com/b/4vsrgc

**Comment by mellowagain** [comment]
looking at what code `autometrics` generates using `cargo expand` reveals the culprit pretty easily:

```rust
let result: std::result::Result<impl ToString> = autometrics::__private::CALLER
                                ^^^^^^^^^^^^^

```

**Comment by gagbo** [comment]
Yeah, I should have seen that coming.

The fix is "basically" expanding [this match statement](https://github.com/autometrics-dev/autometrics-rs/blob/dd902ac2665cdf0c2685f23ab928c8664c2dca27/autometrics-macros/src/lib.rs#L88-L92) so that when the return type is a generic type, it also checks all the type arguments to make sure there's no impl either
